---
- hosts: all

  vars_files:
    - default.config.yml
    - vars_private.yml
  vars:
    source_key: "./files/ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: osx_provisioner.homeshick
      tags: ['dotfiles']
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
      when: configure_dotfiles
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/ssh.yml
      tags: ['ssh']
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']
    - import_tasks: tasks/fonts.yml
      tags: ['fonts']
    - import_tasks: tasks/zsh.yml
      tags: ['zsh']
    - import_tasks: tasks/spacemacs.yml
      tags: ['spacemacs']
    - import_tasks: tasks/tmux.yml
      tags: ['tmux']
    - name: relink homeshick files
      shell:
        cmd: ~/.homesick/repos/homeshick/bin/homeshick link --force dotfiles
    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
