---
- hosts: all

  vars_files:
    - default.config.yml
    - vars_private.yml
  vars:
    source_key: "./files/ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    work: "{{ lookup('env', 'HOME') }}/work"
    github: "{{ lookup('env', 'HOME') }}/github"


  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
    
    - name: Check if running in Parallels VM
      shell: |
        if system_profiler SPHardwareDataType 2>/dev/null | grep -q "Parallels"; then
          echo "true"
        elif ioreg -l | grep -q "Parallels"; then
          echo "true"
        elif [ -f "/System/Library/CoreServices/prl_disp_service" ]; then
          echo "true"
        else
          echo "false"
        fi
      register: parallels_vm_check
      changed_when: false
      tags: ['always']
    
    - name: Set VM fact
      set_fact:
        running_in_vm: "{{ parallels_vm_check.stdout == 'true' }}"
      tags: ['always']
    
    - name: Display VM detection result
      debug:
        msg: "Running in Parallels VM: {{ running_in_vm }}"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
      when: configure_dotfiles
    - role: geerlingguy.mac.mas
      when: (mas_installed_apps or mas_installed_app_ids) and not running_in_vm
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/vm-apps.yml
      tags: ['vm-apps']
    - import_tasks: tasks/ssh.yml
      tags: ['ssh']
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']
    - import_tasks: tasks/fonts.yml
      tags: ['fonts']
    - import_tasks: tasks/zsh.yml
      tags: ['zsh']
    - import_tasks: tasks/asdf.yml
      tags: ['asdf']
    - import_tasks: tasks/spacemacs.yml
      tags: ['spacemacs']
    - import_tasks: tasks/tmux.yml
      tags: ['tmux']
    - import_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']
    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
