---
# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: install .macos script
  copy:
    src: "./files/macos"
    dest: "{{ osx_script }}"
    mode: 0744
  tags:
    - dotfiles
- name: Run .osx dotfiles.
  command: "{{ osx_script }}"
  changed_when: false
